Homepage & Contact Page added
DesignIT-Africa/Tech-Gurus pull request #3
Opened 2023-05-11 11:20 UTC by babsmatic1

Homepage & Contact Page added

2023-05-11 22:16 UTC, DeleMike requested changes
Hi @babsmatic1 , thanks for the PR.
Please you will need to work on this to make some adjustments. 

See screenshots, this is how they appear on my laptop screen


![Screenshot (214)](https://github.com/DesignIT-Africa/Tech-Gurus/assets/49593618/89e6eab2-4fb4-4755-8f30-521fa767bca5)
![Screenshot (215)](https://github.com/DesignIT-Africa/Tech-Gurus/assets/49593618/ee05c140-ce1c-43c9-a3b3-62329ec211dd)

![Screenshot (216)](https://github.com/DesignIT-Africa/Tech-Gurus/assets/49593618/2ac34fff-2c48-4cb4-831b-ee75f6ec9491)
![Screenshot (213)](https://github.com/DesignIT-Africa/Tech-Gurus/assets/49593618/11845f5d-31de-45df-a097-43f731f33f71)

Make changes and just push, I will pull and review again

Please @ade555 , check this out too.

2023-05-11 23:57 UTC, babsmatic1 commented
Okay thanks for the correction i will also review it in another browser indeed cause most. Of them appear normal and stable.

Thanks for the correction

2023-05-12 09:36 UTC, DeleMike commented
> Okay thanks for the correction i will also review it in another browser indeed cause most. Of them appear normal and stable.
> 
> Thanks for the correction

Yeah, you can use Edge browser, that is what I use mostly.

2023-05-15 13:56 UTC, DesignITAfrica requested changes

2023-05-15 14:03 UTC, ade555 requested changes
I appreciate you using semantic tags in some places, but overall, you still need to improve the accessibility of the site. Here are some resources:

1. [Understanding HTML Techniques for Improving Web Accessibility](https://www.makeuseof.com/essential-html-techniques-for-improving-web-accessibility/).
2. [HTML Accessibility by W3Schools](https://www.w3schools.com/html/html_accessibility.asp)

2023-05-25 12:00 UTC, ade555 requested changes

2023-05-25 12:00 UTC, ade555 commented on index.html
> +                <img src="img/partner 1.png" alt="" > &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
I have mentioned accessibility several times but you still do not have alt texts for your images?

2023-05-25 12:26 UTC, babsmatic1 commented
I will do that sir

On Thu, May 25, 2023, 1:00 PM SuperheroJT ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In index.html
> <https://github.com/DesignIT-Africa/Tech-Gurus/pull/3#discussion_r1205411514>
> :
>
> > +    </section>
> +
> +    <!-- Partner Section -->
> +    <div class="story">
> +        <h4>Our Partners</h4>
> +        <hr>
> +    </div><br>
> +    <section class="Partner">
> +        <div class="dishes">
> +            <h3 class="explore">Our Trusted<hr width="110px"></h3>
> +            <h3 class="explore">Partners</h3>
> +        </div><br>
> +
> +            <div class="filder">
> +
> +                <img src="img/partner 1.png" alt="" > &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
>
> I have mentioned accessibility several times but you still do not have alt
> texts for your images?
> ------------------------------
>
> In index.html
> <https://github.com/DesignIT-Africa/Tech-Gurus/pull/3#discussion_r1205409754>
> :
>
> > +                    <li><a href="#" class="link">About Us</a></li>
> +                    <li><a href="./contact.html" class="link">Contact Us </a></li>
> +                    <li><a href="#"><i class="fas fa-cart-shopping"></i></a></li>
> +                </ul>
> +            </div>
> +        </nav>
> +    </header>
> +
> +    <!-- Here is the Hero section -->
> +    <section class="hero">
> +        <h1>Get the best hygienic, afforable and sumptuous meal ever</h1>
> +        <p>Fresh Meals || Swift Delivery || Best Meal Experience</p>
> +        <button class="view">View Our Menu</button> &nbsp;&nbsp;&nbsp;&nbsp;
> +        <button class="book">Order Now</button>
> +    </section>
> +    <br><br>
>
> @babsmatic1 <https://github.com/babsmatic1>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DesignIT-Africa/Tech-Gurus/pull/3#pullrequestreview-1443724207>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQ3UUIQU7AJSHWY36YCASPDXH5CWVANCNFSM6AAAAAAX57QPLM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-25 16:07 UTC, DeleMike commented on index.html
@babsmatic1 kindly adjust as Thompson mentioned

2023-05-25 16:15 UTC, DeleMike commented
Okay, then send in the preview link. Either comment it or share on the
Slack channel so that we can continue the process

On Thu, 25 May 2023, 17:13 Babatunde Abdullahi, ***@***.***>
wrote:

> I have done so sir
>
> On Thu, May 25, 2023, 5:08 PM Akindele Michael ***@***.***>
> wrote:
>
> > ***@***.**** commented on this pull request.
> > ------------------------------
> >
> > On index.html
> > <
> https://github.com/DesignIT-Africa/Tech-Gurus/pull/3#discussion_r1205737895
> >
> > :
> >
> > @babsmatic1 <https://github.com/babsmatic1> kindly adjust as Thompson
> > mentioned
> >
> > —
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/DesignIT-Africa/Tech-Gurus/pull/3#pullrequestreview-1444237165
> >,
> > or unsubscribe
> > <
> https://github.com/notifications/unsubscribe-auth/AQ3UUIQD3NETCHBX2TDLIT3XH57WFANCNFSM6AAAAAAX57QPLM
> >
> > .
> > You are receiving this because you were mentioned.Message ID:
> > ***@***.***>
> >
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DesignIT-Africa/Tech-Gurus/pull/3#issuecomment-1563170316>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AL2L2ETHHTNH476NWCIWCQTXH6ALTANCNFSM6AAAAAAX57QPLM>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2023-06-16 11:02 UTC, DeleMike commented
The intern is not with us.

2023-06-16 11:02 UTC, closed without merging

2023-06-16 12:03 UTC, ade555 commented
Kindly delete the PR. Thanks.

On Fri, Jun 16, 2023 at 12:03 PM Akindele Michael ***@***.***>
wrote:

> The intern is not with us.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DesignIT-Africa/Tech-Gurus/pull/3#issuecomment-1594502079>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQJ6VH3LSVPPPJWLVXGKY3TXLQ4OTANCNFSM6AAAAAAX57QPLM>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>